### ISSUE TITLE
Future-proofing for future semesters' information

### ISSUE THREAD

**Issue by jerryand100** [course-planner/course-planner#20]
Summary: I am curious as to how you plan on updating information in future semesters.

Description: When we pulled the code from the repo, all of the needed PDFs and databases were set up with all past information. I am curious how information for new semesters will be loaded into the application. 

Severity: Trivial (for the moment)

Reasoning: Creating a clean, user-friendly way to update course history information will be important for future continued use of the extension. 

Suggestion: One way to do this could be to have a public-facing server hold an updated version of the database with all the latest information, and include a way in the extension for the user to grab the newest version of the database from this server.

**Comment by JDKardia** [comment]
So are you saying for updating the extension itself with new information from timetables and grade distributions? 

Because if so, what will happen is we will grab the new PDFs that will be made available, put new lines into our Database generation scripts, and then update the database in the github repo. Then we pack up the extension with the updated database, and submit the new version to the Chrome Store, where very shortly we will have our extension available. 

Chrome then automatically handles the updating of the extension in users' browsers.
